import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
var Liban = "liban"
export const metadata = {
 
  title: "Create Next App",
  description: "Generated by create next app",
};
console.log('metadata');
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
