#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Run ESLint on all staged JavaScript/TypeScript files
npx eslint .



# Run Prettier to format code
npx prettier --write .

# Run additional checks or scripts as needed