name: Hello World

on:
  pull_request:
    branches: 
      - main

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Say Hello
        run: echo "Hello World"
