name: Hello World

on:
  pull_request:
    branches: 
      - main

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: build the image
        run: docker build -t first_image

      - name: run the cointainer with lint
        run: docker run first_image npm run lint